#program withot loop
print("Nipuna Technologies")
print("Nipuna Technologies")
print("Nipuna Technologies")
print("Nipuna Technologies")
print("Nipuna Technologies")
print("Nipuna Technologies")
print("Nipuna Technologies")
print("Nipuna Technologies")
print("Nipuna Technologies")
print("Nipuna Technologies")